### ISSUE TITLE
Can run LEAKEY

### ISSUE THREAD

**Issue by liviooo** [rohsec/LEAKEY#1]
Installation went smooth on MacOS.

Unfortunately can't run it with just 'leakey'.

This gives an error:
% ./LEAKEY/leakey.sh 
./LEAKEY/leakey.sh: line 47: syntax error in conditional expression: unexpected token `('
./LEAKEY/leakey.sh: line 47: syntax error near `?(-'
./LEAKEY/leakey.sh: line 47: `    if [[ $choice != "" ]] && [[ $choice = ?(-)+([0-9]) ]] && [ $choice -lt $(cat $sign_dir|jq length) ]'

**Comment by KiltzX** [comment]
Same here

Running MacOs Ventura 13.6.1

**Comment by rynosec** [comment]
Hi @liviooo @KiltzX,
Are you having issues running the script ? I am sorry, can you confirm which shell you both are using? I don't have a Mac and don't have much experience with MacOs default $SHELL, this was just a quick attempt to write clean BASH script, I will try to look into this.
Also, I will be pushing a python version of the same in a day or two that should work completely fine on your side.

Thanks and Regards,

**Comment by rynosec** [comment]
Hi, I guess the issue was due to the regex ```?(-)+([0-9])``` which might be behaving differently or not be enabled by default in macOS's Bash shell.
I have now used an alternative regex pattern, hope this will fix the issue. Please let me know.

Thanks and Regards,

**Comment by KiltzX** [comment]
This works now, thanks @rohsec
